apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ha-postgres
  namespace: ha-postgres

spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:16.10-system-trixie
  imagePullPolicy: IfNotPresent

  bootstrap:
    initdb:
      database: app
      owner: app

  storage:
    storageClass: nfs-csi
    size: 1Gi

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname

  failoverDelay: 0

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
